CREATE SCHEMA maestro

CREATE TABLE maestro.Tasks(
	Id BINARY(16) NOT NULL PRIMARY KEY,
	[Type] TINYINT NOT NULL,
	[Input] VARBINARY(MAX) NOT NULL,
	InputType VARCHAR(500) NOT NULL,
	AckCode BINARY(20) NOT NULL,
	AckValueType VARCHAR(500) NOT NULL,
	GroupId BINARY(16) NULL,
	HandlerType VARCHAR(500) NOT NULL,
	CreatedAt DATETIME2 NOT NULL,
	CompletedAt DATETIME2 NULL,
);

CREATE TYPE maestro.TaskType AS TABLE(
	Id BINARY(16) NOT NULL PRIMARY KEY,
	[Type] TINYINT NOT NULL,
	[Input] VARBINARY(MAX) NOT NULL,
	InputType VARCHAR(500) NOT NULL,
	AckCode BINARY(20) NOT NULL,
	AckValueType VARCHAR(500) NOT NULL,
	GroupId BINARY(16) NULL,
	HandlerType VARCHAR(500) NOT NULL,
	CreatedAt DATETIME2 NOT NULL
);

CREATE TABLE maestro.Acks(
	Code BINARY(20) NOT NULL PRIMARY KEY,
	[Value] VARBINARY(MAX) NOT NULL,
	ValueType VARCHAR(500) NOT NULL,
	CreatedAt DATETIME2 NOT NULL
);

CREATE TYPE maestro.AckType AS TABLE(
	Code BINARY(20) NOT NULL PRIMARY KEY,
	[Value] VARBINARY(MAX) NOT NULL,
	ValueType VARCHAR(500) NOT NULL,
	CreatedAt DATETIME2 NOT NULL
);

CREATE TABLE maestro.TaskWaitAcks(
	TaskId BINARY(16) NOT NULL,
	Code BINARY(20) NOT NULL,
	PRIMARY KEY(TaskId, Code)
);

CREATE TABLE maestro.TaskCompleteAcks(
	TaskId BINARY(16) NOT NULL,
	Code BINARY(20) NOT NULL,
	PRIMARY KEY(TaskId, Code)
);

CREATE TYPE maestro.TaskAckType AS TABLE(
	TaskId BINARY(16) NOT NULL,
	Code BINARY(20) NOT NULL,
	PRIMARY KEY(TaskId, Code)
);
