DROP TABLE maestro.Tasks;
DROP TABLE maestro.Acks;
DROP TABLE maestro.TaskWaitAcks;
DROP TABLE maestro.TaskCompleteAcks;

DROP TYPE maestro.TaskType;
DROP TYPE maestro.AckType;
DROP TYPE maestro.TaskAckType;

DROP SCHEMA maestro;

CREATE SCHEMA maestro;

CREATE TABLE maestro.Tasks(
	Id BINARY(16) NOT NULL PRIMARY KEY,
	[Type] TINYINT NOT NULL,
	[Input] VARBINARY(MAX) NOT NULL,
	InputType NVARCHAR(500) NOT NULL,
	AckCode BINARY(20) NOT NULL,
	AckValueType NVARCHAR(500) NOT NULL,
	GroupId BINARY(16) NULL,
	HandlerType NVARCHAR(500) NOT NULL,
	CreatedAt DATETIME2 NOT NULL,
	CompletedAt DATETIME2 NULL,
);

CREATE TYPE maestro.TaskType AS TABLE(
	Id BINARY(16) NOT NULL PRIMARY KEY,
	[Type] TINYINT NOT NULL,
	[Input] VARBINARY(MAX) NOT NULL,
	InputType NVARCHAR(500) NOT NULL,
	AckCode BINARY(20) NOT NULL,
	AckValueType NVARCHAR(500) NOT NULL,
	GroupId BINARY(16) NULL,
	HandlerType NVARCHAR(500) NOT NULL,
	CreatedAt DATETIME2 NOT NULL
);

CREATE TABLE maestro.Acks(
	Code BINARY(20) NOT NULL PRIMARY KEY,
	[Value] VARBINARY(MAX) NOT NULL,
	ValueType NVARCHAR(500) NOT NULL,
	CreatedAt DATETIME2 NOT NULL
);

CREATE TYPE maestro.AckType AS TABLE(
	Code VARBINARY(20) NOT NULL PRIMARY KEY,
	[Value] VARBINARY(MAX) NOT NULL,
	ValueType NVARCHAR(500) NOT NULL,
	CreatedAt DATETIME2 NOT NULL
);

CREATE TABLE maestro.TaskWaitAcks(
	TaskId BINARY(16) NOT NULL,
	Code BINARY(20) NOT NULL,
	PRIMARY KEY(TaskId, Code)
);

CREATE TABLE maestro.TaskCompleteAcks(
	TaskId BINARY(16) NOT NULL,
	Code BINARY(20) NOT NULL,
	PRIMARY KEY(TaskId, Code)
);

CREATE TYPE maestro.TaskAckType AS TABLE(
	TaskId VARBINARY(16) NOT NULL,
	Code VARBINARY(20) NOT NULL,
	PRIMARY KEY(TaskId, Code)
);

